magick convert result.png -transparent #000000 -alpha extract -negate -depth 8 30.png
magick convert result.png -transparent #010101 -alpha extract -negate -depth 8 00.png
magick convert result.png -transparent #020202 -alpha extract -negate -depth 8 01.png
magick convert result.png -transparent #030303 -alpha extract -negate -depth 8 02.png
magick convert result.png -transparent #040404 -alpha extract -negate -depth 8 03.png
magick convert result.png -transparent #050505 -alpha extract -negate -depth 8 04.png
magick convert result.png -transparent #060606 -alpha extract -negate -depth 8 05.png
magick convert result.png -transparent #070707 -alpha extract -negate -depth 8 06.png
magick convert result.png -transparent #080808 -alpha extract -negate -depth 8 07.png
magick convert result.png -transparent #090909 -alpha extract -negate -depth 8 08.png
magick convert result.png -transparent #0A0A0A -alpha extract -negate -depth 8 09.png
magick convert result.png -transparent #0B0B0B -alpha extract -negate -depth 8 10.png
magick convert result.png -transparent #0C0C0C -alpha extract -negate -depth 8 11.png
magick convert result.png -transparent #0D0D0D -alpha extract -negate -depth 8 12.png
magick convert result.png -transparent #0E0E0E -alpha extract -negate -depth 8 13.png
magick convert result.png -transparent #0F0F0F -alpha extract -negate -depth 8 14.png
magick convert result.png -transparent #101010 -alpha extract -negate -depth 8 15.png
magick convert result.png -transparent #111111 -alpha extract -negate -depth 8 16.png
magick convert result.png -transparent #121212 -alpha extract -negate -depth 8 17.png
magick convert result.png -transparent #131313 -alpha extract -negate -depth 8 18.png
magick convert result.png -transparent #141414 -alpha extract -negate -depth 8 19.png
magick convert result.png -transparent #151515 -alpha extract -negate -depth 8 20.png
magick convert result.png -transparent #161616 -alpha extract -negate -depth 8 21.png
magick convert result.png -transparent #171717 -alpha extract -negate -depth 8 22.png
magick convert result.png -transparent #181818 -alpha extract -negate -depth 8 23.png
magick convert result.png -transparent #191919 -alpha extract -negate -depth 8 24.png
magick convert result.png -transparent #1A1A1A -alpha extract -negate -depth 8 25.png
magick convert result.png -transparent #1B1B1B -alpha extract -negate -depth 8 26.png
magick convert result.png -transparent #1C1C1C -alpha extract -negate -depth 8 27.png
magick convert result.png -transparent #1D1D1D -alpha extract -negate -depth 8 28.png